### ISSUE TITLE
Parawatch Hub Ebook?

### ISSUE THREAD

**Issue by BSCP1981** [lselden/scp-to-epub#4]
Hey there!

Thanks for making so much of the SCP material available in Ebook form!

Just a suggestion, but the Groups of Interest material would be awesome to have in Ebook form, especially the Parawatch and Unusual Incidents Unit hubs. The different Logs (of Extranormal Events, Items, etc.) might be fun Ebook additions as well!

**Comment by lselden** [comment]
Good idea! Added the groups of interest pages to the [latest release](https://github.com/lselden/scp-to-epub/releases/tag/v15-books) - The logs are in the [Various Lists and Logs](https://github.com/lselden/scp-to-epub/releases/download/v15-books/lists-and-logs.epub) ebook.

**Comment by BSCP1981** [comment]
Incredible! Thanks so much! Just goes to show, not all heroes wear capes!

If I was to add one more suggestion, I would say that the individual Hubs for the International Hub section (Italian Hub, German Hub, etc.) would be great to add, since the individual hubs have a lot of entries that aren't on the main International Hub section. 

Besides that, maybe the SCP Classics wiki, with the deleted entries? Other than that, I think this ebook collection is pretty comprehensive at this point! Thanks again for this amazing gift, and right around the Christmas season!
