### ISSUE TITLE
SCP International Branch Hubs

### ISSUE THREAD

**Issue by BSCP1981** [lselden/scp-to-epub#5]
Hello again!

So sorry, I was truly trying not to be a nuisance, but is it possible to make one more request, of the individual International Branch SCP Hubs (Italian Branch, Thai Branch, German Branch, etc.) as seperate ebooks? They have a lot of cool entries that the International Branches ebook you already made is sadly lacking. 

Sorry, I tried to run the program and do it myself, but having technical issues on my end (I saw someone else on Reddit was having similar issues). No pressure either way, but would greatly appreciate it if so!

**Comment by lselden** [comment]
Done! I couldn't get the French branch to load properly - may try later. But put others up along with the Wanderers Library

**Comment by BSCP1981** [comment]
You're incredible! Thank you so much, once again!

The French book is loading fine for me. However, the "International" book is not loading - it just brings up an error message when I try to download it.

**Comment by lselden** [comment]
whoops! thanks, fixed

**Comment by BSCP1981** [comment]
Meant to write back and say that all of the ebooks are working perfectly. Thanks again for making all of this content so easily available in digital ebook form. 

I had one more, perhaps out of the box, suggestion: how about the SCP Classics page, with all the old deleted entries? Not all of them are great, but it would be interesting from a historical perspective.  

http://scpclassic.wikidot.com/
